import React, { useState, useEffect } from 'react';
import api from '../../services/api';
import { useToast } from '../../context/ToastContext';
import { 
  Users, Gift, Copy, Check, TrendingUp, 
  Award, ShieldCheck, Share2, Sparkles, ChevronLeft, ChevronRight 
} from 'lucide-react';

const UserReferrals = () => {
  const { success } = useToast();

  const [summary, setSummary] = useState(null);
  const [activeTab, setActiveTab] = useState('users'); // 'users' or 'commissions'
  const [users, setUsers] = useState([]);
  const [commissions, setCommissions] = useState([]);
  const [page, setPage] = useState(1);
  const [totalPages, setTotalPages] = useState(1);
  const [copied, setCopied] = useState(false);
  const [loading, setLoading] = useState(true);

  const loadSummary = async () => {
    try {
      const res = await api.get('/referrals/summary');
      if (res.data?.data) {
        setSummary(res.data.data);
      }
    } catch (err) {
      console.error('Failed to load referral summary:', err);
    }
  };

  const loadTabData = async () => {
    try {
      setLoading(true);
      if (activeTab === 'users') {
        const res = await api.get(`/referrals/users?page=${page}&pageSize=10`);
        if (res.data?.data) {
          setUsers(res.data.data.items || []);
          setTotalPages(res.data.data.totalPages || 1);
        }
      } else {
        const res = await api.get(`/referrals/commissions?page=${page}&pageSize=10`);
        if (res.data?.data) {
          setCommissions(res.data.data.items || []);
          setTotalPages(res.data.data.totalPages || 1);
        }
      }
    } catch (err) {
      console.error('Failed to load referral tab data:', err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadSummary();
  }, []);

  useEffect(() => {
    loadTabData();
  }, [activeTab, page]);

  const fullReferralUrl = summary?.referralCode
    ? `${window.location.origin}/register?ref=${summary.referralCode}`
    : '';

  const handleCopyLink = () => {
    navigator.clipboard.writeText(fullReferralUrl);
    setCopied(true);
    success('Referral link copied to clipboard!');
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="space-y-8 animate-fade-in">
      {/* Title */}
      <div>
        <h1 className="font-heading font-black text-2xl sm:text-3xl text-slate-100">
          Referral Network <span className="text-gradient-brand">(10% Lifetime)</span>
        </h1>
        <p className="text-xs sm:text-sm text-slate-400 mt-1">
          Share your exclusive referral invitation link and earn 10% instant commission on all task earnings generated by your network.
        </p>
      </div>

      {/* Referral Link Share Card */}
      <div 
        className="p-6 sm:p-8 rounded-3xl relative overflow-hidden glass-card transition-all"
        style={{
          boxShadow: 'var(--theme-glow)'
        }}
      >
        <div 
          className="absolute -right-20 -top-20 w-60 h-60 rounded-full blur-3xl pointer-events-none opacity-20"
          style={{ background: 'var(--theme-gradient-brand)' }}
        />

        <div className="relative z-10 space-y-6">
          <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
            <div className="space-y-1.5">
              <div 
                className="inline-flex items-center gap-2 px-3 py-1 rounded-full text-xs font-bold"
                style={{
                  background: 'color-mix(in srgb, var(--theme-primary) 15%, transparent)',
                  color: 'var(--theme-primary)',
                  border: '1px solid color-mix(in srgb, var(--theme-primary) 30%, transparent)'
                }}
              >
                <Gift className="w-3.5 h-3.5 text-amber-400" />
                <span>Tier-1 Partner Revenue Share Active</span>
              </div>
              <h3 className="font-heading font-black text-xl text-slate-100">
                Your Personal Referral Link & Code
              </h3>
            </div>

            <div 
              className="px-5 py-2.5 rounded-2xl text-center"
              style={{
                background: 'var(--theme-bg-surface)',
                border: '1px solid var(--theme-border)'
              }}
            >
              <p className="text-[10px] uppercase font-bold text-slate-400">Referral Code</p>
              <p className="text-lg font-mono font-black text-amber-300">{summary?.referralCode || '...'}</p>
            </div>
          </div>

          {/* Copy Box */}
          <div className="flex flex-col sm:flex-row gap-3">
            <input
              type="text"
              readOnly
              value={fullReferralUrl}
              className="flex-1 px-4 py-3.5 rounded-2xl text-xs font-mono text-slate-200 focus:outline-none select-all"
              style={{
                background: 'var(--theme-bg-main)',
                border: '1px solid var(--theme-border)'
              }}
            />
            <button
              onClick={handleCopyLink}
              className="px-6 py-3.5 rounded-2xl text-white font-bold text-xs flex items-center justify-center gap-2 transition-all shrink-0 hover:scale-[1.02] active:scale-95 shadow-lg"
              style={{
                background: 'var(--theme-gradient-brand)',
                boxShadow: 'var(--theme-glow)'
              }}
            >
              {copied ? <Check className="w-4 h-4 text-emerald-300" /> : <Copy className="w-4 h-4" />}
              <span>{copied ? 'Link Copied!' : 'Copy Invitation Link'}</span>
            </button>
          </div>
        </div>
      </div>

      {/* Summary KPI Cards */}
      <div className="grid grid-cols-1 sm:grid-cols-3 gap-5">
        <div 
          className="p-6 rounded-3xl glass-card space-y-2 transition-all"
          style={{ background: 'var(--theme-bg-surface)' }}
        >
          <div className="flex items-center justify-between text-xs font-semibold text-slate-400">
            <span>Total Friends Invited</span>
            <Users className="w-5 h-5" style={{ color: 'var(--theme-primary)' }} />
          </div>
          <p className="text-3xl font-black font-heading text-slate-100">{summary?.totalReferrals || 0}</p>
          <p className="text-[11px] text-slate-400">Registered users in your direct network</p>
        </div>

        <div 
          className="p-6 rounded-3xl glass-card space-y-2 transition-all"
          style={{ background: 'var(--theme-bg-surface)' }}
        >
          <div className="flex items-center justify-between text-xs font-semibold text-emerald-400">
            <span>Active Participants</span>
            <ShieldCheck className="w-5 h-5 text-emerald-400" />
          </div>
          <p className="text-3xl font-black font-heading text-emerald-400">{summary?.activeReferrals || 0}</p>
          <p className="text-[11px] text-slate-400">Completing daily sponsored campaigns</p>
        </div>

        <div 
          className="p-6 rounded-3xl glass-card space-y-2 transition-all"
          style={{ background: 'var(--theme-bg-surface)' }}
        >
          <div className="flex items-center justify-between text-xs font-semibold text-amber-400">
            <span>Total Commission Earned</span>
            <Award className="w-5 h-5 text-amber-400" />
          </div>
          <p className="text-3xl font-black font-heading text-amber-300">
            {Number(summary?.totalCommissionEarned || 0).toLocaleString(undefined, { minimumFractionDigits: 2 })} <span className="text-sm font-normal text-slate-400">PKR</span>
          </p>
          <p className="text-[11px] text-slate-400">Instant direct payouts to your main wallet</p>
        </div>
      </div>

      {/* Tabs & Table */}
      <div 
        className="p-6 rounded-3xl glass-card space-y-6"
        style={{ background: 'var(--theme-bg-surface)' }}
      >
        {/* Tab Switcher */}
        <div className="flex items-center gap-3 border-b border-slate-800/80 pb-4">
          <button
            onClick={() => { setActiveTab('users'); setPage(1); }}
            className={`px-4 py-2 rounded-xl text-xs font-bold transition-all ${
              activeTab === 'users'
                ? 'text-white shadow'
                : 'text-slate-400 hover:text-white'
            }`}
            style={
              activeTab === 'users'
                ? {
                    background: 'var(--theme-gradient-brand)',
                    boxShadow: 'var(--theme-glow)'
                  }
                : {}
            }
          >
            Referred Network ({summary?.totalReferrals || 0})
          </button>
          <button
            onClick={() => { setActiveTab('commissions'); setPage(1); }}
            className={`px-4 py-2 rounded-xl text-xs font-bold transition-all ${
              activeTab === 'commissions'
                ? 'text-white shadow'
                : 'text-slate-400 hover:text-white'
            }`}
            style={
              activeTab === 'commissions'
                ? {
                    background: 'var(--theme-gradient-brand)',
                    boxShadow: 'var(--theme-glow)'
                  }
                : {}
            }
          >
            Commission Ledger History
          </button>
        </div>

        {/* Tab 1: Network Users */}
        {activeTab === 'users' && (
          <div className="overflow-x-auto">
            <table className="w-full text-left text-xs">
              <thead>
                <tr className="border-b border-slate-800/80 text-slate-400 font-bold uppercase tracking-wider">
                  <th className="pb-3 px-3">User</th>
                  <th className="pb-3 px-3">Joined Date</th>
                  <th className="pb-3 px-3 text-center">Account Status</th>
                  <th className="pb-3 px-3 text-right">Commission Generated</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-800/60 font-medium">
                {users.length > 0 ? (
                  users.map((u) => (
                    <tr key={u.userId} className="hover:bg-white/[0.02] transition-colors">
                      <td className="py-3 px-3 text-slate-100 font-bold">
                        <p>{u.fullName}</p>
                        <p className="text-[10px] text-slate-500 font-mono">@{u.username}</p>
                      </td>
                      <td className="py-3 px-3 text-slate-400">
                        {new Date(u.joinedAt).toLocaleDateString()}
                      </td>
                      <td className="py-3 px-3 text-center">
                        <span className={`px-2.5 py-0.5 rounded-full text-[10px] font-bold ${
                          u.status === 'Active'
                            ? 'bg-emerald-950 text-emerald-400 border border-emerald-800/50'
                            : 'bg-rose-950 text-rose-300 border border-rose-800/50'
                        }`}>
                          {u.status}
                        </span>
                      </td>
                      <td className="py-3 px-3 text-right font-bold text-amber-300 font-heading">
                        +{Number(u.totalGeneratedCommission).toLocaleString(undefined, { minimumFractionDigits: 2 })} PKR
                      </td>
                    </tr>
                  ))
                ) : (
                  <tr>
                    <td colSpan="4" className="text-center py-10 text-slate-500">
                      No referred users found yet. Share your invitation link above to invite friends!
                    </td>
                  </tr>
                )}
              </tbody>
            </table>
          </div>
        )}

        {/* Tab 2: Commission History */}
        {activeTab === 'commissions' && (
          <div className="overflow-x-auto">
            <table className="w-full text-left text-xs">
              <thead>
                <tr className="border-b border-slate-800/80 text-slate-400 font-bold uppercase tracking-wider">
                  <th className="pb-3 px-3">Date</th>
                  <th className="pb-3 px-3">Referred User</th>
                  <th className="pb-3 px-3 text-right">Task Reward</th>
                  <th className="pb-3 px-3 text-right">Commission %</th>
                  <th className="pb-3 px-3 text-right">Your 10% Commission</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-800/60 font-medium">
                {commissions.length > 0 ? (
                  commissions.map((c) => (
                    <tr key={c.id} className="hover:bg-white/[0.02] transition-colors">
                      <td className="py-3 px-3 text-slate-400">
                        {new Date(c.createdAt).toLocaleString()}
                      </td>
                      <td className="py-3 px-3 font-mono font-bold" style={{ color: 'var(--theme-primary)' }}>
                        @{c.referredUsername}
                      </td>
                      <td className="py-3 px-3 text-right text-slate-300 font-heading">
                        {Number(c.taskRewardAmount).toFixed(2)} PKR
                      </td>
                      <td className="py-3 px-3 text-right text-slate-400 font-mono">
                        {c.commissionPercentage}%
                      </td>
                      <td className="py-3 px-3 text-right font-bold text-emerald-400 font-heading">
                        +{Number(c.commissionAmount).toFixed(2)} PKR
                      </td>
                    </tr>
                  ))
                ) : (
                  <tr>
                    <td colSpan="5" className="text-center py-10 text-slate-500">
                      No referral commissions recorded yet.
                    </td>
                  </tr>
                )}
              </tbody>
            </table>
          </div>
        )}

        {/* Pagination */}
        {totalPages > 1 && (
          <div className="pt-4 border-t border-slate-800/80 flex items-center justify-between text-xs text-slate-400">
            <span>Page {page} of {totalPages}</span>
            <div className="flex gap-2">
              <button
                disabled={page <= 1}
                onClick={() => setPage((p) => Math.max(1, p - 1))}
                className="p-1.5 rounded-lg border border-slate-800 hover:bg-slate-800 disabled:opacity-30"
              >
                <ChevronLeft className="w-4 h-4" />
              </button>
              <button
                disabled={page >= totalPages}
                onClick={() => setPage((p) => Math.min(totalPages, p + 1))}
                className="p-1.5 rounded-lg border border-slate-800 hover:bg-slate-800 disabled:opacity-30"
              >
                <ChevronRight className="w-4 h-4" />
              </button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};

export default UserReferrals;
